config/routes.rb
Rails.application.routes.draw do
  resources :dictionaries

  root 'dictionaries#index'

end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  default_scope { order(word: :asc) }
  validates :word, :meaning, presence: true, :uniqueness => {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @searchText = params[:searchText]
    if @searchText.blank?
      @dictionaries = Dictionary.all
    else
      table = Dictionary.arel_table
      search_pattern = "%#{@searchText}%"
      # TODO: Need to sanitize params against sql-injection?
      @dictionaries = Dictionary.where((table[:word].matches(search_pattern)).or(table[:meaning].matches(search_pattern)))
    end
    @dictionaries = @dictionaries.page(params[:page]).per(5)
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dictionary
    @dictionary = Dictionary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dictionary_params
    params.require(:dictionary).permit(:word, :meaning)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_dictionary_table.html.haml
%table.table.table-striped.table-bordered.table-hover.table-condensed
  %tr
    %th id
    %th Word
    %th Meaning
    %th{colspan: 3} Actions

  - dictionaries.each do |dictionary|
    %tr
      %td= dictionary.id
      %td= dictionary.word
      %td= dictionary.meaning
      %td= link_to 'Show', dictionary
      %td= link_to 'Edit', edit_dictionary_path(dictionary)
      %td= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' }

app/views/dictionaries/_form.html.haml
= form_for(@dictionary, html: { class: "form-horizontal", role: "form" }) do |f|
  = render 'shared/error_messages', model: @dictionary

  .form-group.field
    = f.label :word, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :word, class: "form-control"
  .form-group.field
    = f.label :meaning, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :meaning, class: "form-control"
  .form-group.field
    .col-sm-offset-2.col-sm-10
      = f.submit 'Save', class: "btn btn-default btn-success"

app/views/dictionaries/edit.html.haml
.panel.panel-default
  .panel-heading
    .page-header
      %h3 Editing dictionary

  .panel-body
    = render 'form'
    %a.btn.btn-default{href: dictionary_path(@dictionary)} Show
    %a.btn.btn-default{href: dictionaries_path} Back

app/views/dictionaries/index.html.haml
.panel.panel-default
  .panel-heading
    .page-header
      %h3 Listing dictionaries

  .panel-body
    #dictionary-search.search.navbar
      %form#search.navbar-form.navbar.navbar-left{action: dictionaries_path, method: "get"}
        %input.form-control#searchText{name: "searchText", placeholder: "Search partial match on word/meaning", type: "text", size: 40, value: @searchText}
        %button.btn.btn-default{type: "submit"} Submit
      %a.btn.btn-primary.navbar-right{href: new_dictionary_path} New Dictionary

    %br
    .dictionary_table
      = render 'dictionary_table', dictionaries: @dictionaries
    %br
    .paginator
      = paginate @dictionaries, remote: true
      %br
      = page_entries_info @dictionaries

app/views/dictionaries/index.js.haml
$(".dictionary_table").html('#{escape_javascript(render "dictionary_table", dictionaries: @dictionaries)}');
$('.paginator').html('#{escape_javascript(paginate(@dictionaries, :remote => true))}<br/> ');
$('.paginator').append('#{escape_javascript(page_entries_info @dictionaries)}');

app/views/dictionaries/new.html.haml
.panel.panel-default
  .panel-heading
    .page-header
      %h3 New dictionary

  .panel-body
    = render 'form'
    %a.btn.btn-default.navbar-left{href: dictionaries_path} Back

app/views/dictionaries/show.html.haml
.panel.panel-default
  .panel-heading
    .page-header
      %h3 Show dictionary

  .panel-body
    %p#notice= notice

    .row
      %label.col-sm-2 Word
      = @dictionary.word

    .row
      %label.col-sm-2 Meaning
      = @dictionary.meaning

    %a.btn.btn-default{href: edit_dictionary_path(@dictionary)} Edit
    %a.btn.btn-default{href: dictionaries_path} Back

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Solthiruthi
    = stylesheet_link_tag    'application', media: 'all', data: { 'turbolinks-track' => true }
    = javascript_include_tag 'application', data: { 'turbolinks-track' => true }
    = csrf_meta_tags
  %body
    / Most of the navbar, etc is based on code examples from here: http://getbootstrap.com/components
    %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle{data: {target: "#bs-example-navbar-collapse-1", toggle: "collapse"}, type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path} Solthiruthi
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{href: dictionaries_path} Dictionaries

    .content
      %br
      = yield

app/views/shared/_error_messages.html.haml
- if model.errors.any?
  #error_explanation
    %h2= "#{pluralize(model.errors.count, "error")} prohibited this #{model.class.name.downcase} from being saved:"
    %ul
      - model.errors.full_messages.each do |msg|
        %li= msg